### ISSUE TITLE
two repositories for development of playscii?

### ISSUE THREAD

**Issue by nnako** [michael-lazar/playscii#1]
Hi,

I became interested in PLAYSCII but still confused about the fact that there seem to be at least two repositories used for hosting current source code:

- https://heptapod.host/jp-lebreton/playscii
- https://github.com/michael-lazar/playscii

which one is the "right" one? does anybody know why this situation (two repos) is the case?

**Comment by michael-lazar** [comment]
Hi @nnako 

This github repository is my personal fork of playscii. You want the official one which is at https://heptapod.host/jp-lebreton/playscii
