### ISSUE TITLE
Background color isn't working

### ISSUE THREAD

**Issue by Katdotbrush** [michael-lazar/playscii#4]
I was trying to do a PETSCII Sword, perhaps, when I tried to make the background color another color, it didn't change, it stayed black (default)
![image](https://github.com/michael-lazar/playscii/assets/134107820/6155a4cf-52e8-4182-96d8-cd622f22b659)

**Comment by michael-lazar** [comment]
This github repository is my personal fork of playscii. You want the official one which is at https://heptapod.host/jp-lebreton/playscii
